name: fancy_animated_list
description: A Flutter package providing customizable and animated list views with smooth transitions.
version: 1.0.0
homepage: https://github.com/nightmadwar/fancy_animated_list
author: Maher Madwar Maher@iust.club
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
